### ISSUE TITLE
a built-in alternative method

### ISSUE THREAD

**Issue by naturallymitchell** [tophf/history-omnibox#1]
thank you for this addon
here's an alternative method
it doesn't support suggestions though

add search engine: `chrome://history/?q=%s`
more info: [Make Chrome prioritize history results over search suggestions in omnibox](https://superuser.com/questions/802597/make-chrome-prioritize-history-results-over-search-suggestions-in-omnibox)

**Comment by tophf** [comment]
Yeah, of course, but the point of this extension is the interactive suggestions.
